name: kiss_clock
description: Keep It Simple, Stupid. (Clock)
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  provider: ^4.0.1
  number_to_words: ^0.0.3
  dartx: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1
  effective_dart: ^1.2.1
  lint: ^1.1.1

flutter:
  uses-material-design: true

  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/roboto_mono/RobotoMono-Thin.ttf
          style: normal
          weight: 100

        - asset: assets/fonts/roboto_mono/RobotoMono-ThinItalic.ttf
          style: italic
          weight: 100

        - asset: assets/fonts/roboto_mono/RobotoMono-Light.ttf
          style: normal
          weight: 300

        - asset: assets/fonts/roboto_mono/RobotoMono-LightItalic.ttf
          style: italic
          weight: 300

        - asset: assets/fonts/roboto_mono/RobotoMono-Regular.ttf
          style: normal
          weight: 400

        - asset: assets/fonts/roboto_mono/RobotoMono-Italic.ttf
          style: italic
          weight: 400

        - asset: assets/fonts/roboto_mono/RobotoMono-Medium.ttf
          style: normal
          weight: 500

        - asset: assets/fonts/roboto_mono/RobotoMono-MediumItalic.ttf
          style: italic
          weight: 500

        - asset: assets/fonts/roboto_mono/RobotoMono-Bold.ttf
          style: normal
          weight: 700

        - asset: assets/fonts/roboto_mono/RobotoMono-BoldItalic.ttf
          style: italic
          weight: 700
